#!/usr/bin/env ruby
child = fork do
  $0 = 'bashobot'
  $: << File.expand_path("../lib", __FILE_)_
  require 'rubygems'
  require 'bundler/setup'
  require 'bashobot'

  BashoBot.start
end
Process.detach(child)
