#!/usr/bin/env ruby
$0 = 'bashobot'
$: << File.expand_path("../lib", __FILE__)
require 'rubygems'
require 'bundler/setup'
require 'bashobot'

Process.daemon(true) unless ENV['BASHOBOT'] == 'test'

BashoBot.start
